# Generated by Django 3.2.4 on 2021-06-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Free',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
            ],
            options={
                'verbose_name': '자유게시판',
                'verbose_name_plural': '자유게시판',
                'db_table': '자유게시판',
            },
        ),
    ]
