# Generated by Django 3.2.3 on 2021-05-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='anonymous',
        ),
        migrations.AlterField(
            model_name='article',
            name='state',
            field=models.CharField(choices=[('ing', '모집중'), ('complete', '모집완료')], max_length=20),
        ),
    ]
