# Generated by Django 3.2.4 on 2021-06-28 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Large_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Medium_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('large_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.large_category')),
            ],
        ),
        migrations.CreateModel(
            name='Small_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('medium_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.medium_category')),
            ],
        ),
    ]
