# Generated by Django 3.2.4 on 2021-06-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210619_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normaluser',
            options={'verbose_name': '쿨괜 사용자', 'verbose_name_plural': '쿨괜 사용자'},
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='password',
            field=models.CharField(max_length=64, verbose_name='비밀번호'),
        ),
    ]
