# Generated by Django 3.2.3 on 2021-05-29 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('ten', '10대'), ('twenty', '20대'), ('third', '30대'), ('forty', '40대'), ('fifty', '50대 이상')], max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('kakao_url', models.CharField(max_length=200)),
                ('headcount', models.IntegerField()),
                ('state', models.CharField(choices=[('ing', '모집중'), ('complete', '모집완료')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
