# Generated by Django 3.2.4 on 2021-06-28 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('category', models.CharField(default=1, max_length=20, verbose_name='카테고리')),
                ('area', models.CharField(max_length=20, verbose_name='위치')),
                ('age', models.CharField(default=1, max_length=20, verbose_name='연령대')),
                ('meeting_date', models.CharField(max_length=20, verbose_name='만남 시간')),
                ('headcount', models.IntegerField(verbose_name='모집인원')),
                ('state', models.CharField(default=1, max_length=20, verbose_name='모집상태')),
                ('body', models.TextField(verbose_name='내용')),
                ('kakao_url', models.CharField(max_length=200, verbose_name='오픈카톡 url')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '쿨괜 게시판',
                'verbose_name_plural': '쿨괜 게시판',
                'db_table': 'cool_board',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='article.article')),
            ],
            options={
                'verbose_name': '쿨괜 게시판_댓글',
                'verbose_name_plural': '쿨괜 게시판_댓글',
                'db_table': 'cool_board_comment',
            },
        ),
    ]
