# Generated by Django 3.2.4 on 2021-06-19 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0003_delete_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='age',
            field=models.CharField(choices=[('ten', '10대'), ('twenty', '20대'), ('third', '30대'), ('forty', '40대'), ('fifty', '50대 이상')], max_length=20, verbose_name='연령대'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
