# Generated by Django 3.2.4 on 2021-06-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210619_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '쿨괜 게시판', 'verbose_name_plural': '쿨괜 게시판'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='writer',
        ),
        migrations.AlterField(
            model_name='article',
            name='age',
            field=models.CharField(default=1, max_length=20, verbose_name='연령대'),
        ),
        migrations.AlterField(
            model_name='article',
            name='area',
            field=models.CharField(max_length=20, verbose_name='위치'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(default=1, max_length=20, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='article',
            name='headcount',
            field=models.IntegerField(verbose_name='모집인원'),
        ),
        migrations.AlterField(
            model_name='article',
            name='kakao_url',
            field=models.CharField(max_length=200, verbose_name='오픈카톡 url'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meeting_date',
            field=models.CharField(max_length=20, verbose_name='만남 시간'),
        ),
        migrations.AlterField(
            model_name='article',
            name='state',
            field=models.CharField(default=1, max_length=20, verbose_name='모집상태'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='cool_board',
        ),
    ]
