# Generated by Django 3.2.4 on 2021-06-24 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0005_auto_20210620_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200, verbose_name='댓글 본문')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='댓글 작성자')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='댓글 작성자')),
            ],
            options={
                'verbose_name': '쿨괜 게시판_댓글',
                'verbose_name_plural': '쿨괜 게시판_댓글',
                'db_table': 'cool_board_comment',
            },
        ),
    ]
