# Generated by Django 3.2.4 on 2021-06-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
