# Generated by Django 3.0.8 on 2021-05-26 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('article', '0006_alter_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='category_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
