# Generated by Django 3.2.4 on 2021-06-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20210625_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='writer',
            new_name='author',
        ),
    ]
