# Generated by Django 3.0.8 on 2021-05-26 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('article', '0007_auto_20210526_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category_type',
        ),
        migrations.AddField(
            model_name='article',
            name='edium_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Medium_category'),
        ),
        migrations.AddField(
            model_name='article',
            name='large_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Large_category'),
        ),
        migrations.AddField(
            model_name='article',
            name='small_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Small_category'),
        ),
    ]
