# Generated by Django 3.2.3 on 2021-05-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_merge_0005_comment_0009_alter_article_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='edium_category',
            new_name='medium_category',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=200),
        ),
    ]
