# Generated by Django 3.2.4 on 2021-06-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20210626_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(default=1, max_length=20, verbose_name='카테고리'),
        ),
    ]
