# Generated by Django 3.2.3 on 2021-05-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_alter_article_meeting_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='meeting_time',
            new_name='meeting_date',
        ),
    ]
