# Generated by Django 3.2.3 on 2021-05-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_rename_meeting_time_article_meeting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='large_category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='medium_category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='small_category',
        ),
    ]
