# Generated by Django 3.2.3 on 2021-05-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20210528_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='meeting_date',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
