# Generated by Django 3.2.4 on 2021-06-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20210627_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='board',
        ),
    ]
